### ISSUE TITLE
Doppelte String-Ressource 

### ISSUE THREAD

**Issue by behrends** [luk-pe/BullshitBingo#2]
`created_by` wird zweimal deklariert (gefunden in Android Studio durch `Analyze > Inspect Code…`)
https://github.com/luk-pe/BullshitBingo/blob/521b8f1b45c28bb03cac765488cab6481afaff8b/app/src/main/res/values/strings.xml#L20-L26

**Comment by luk-pe** [comment]
Bug durch merge Fehler, behoben durch Commit 893bc254266f581dcc5b84f368f00f2ae1a9d8b4
