### ISSUE TITLE
Unnötiger Boolean-Vergleich 

### ISSUE THREAD

**Issue by behrends** [luk-pe/BullshitBingo#3]
`== true` kann weggelassen werden (gefunden in Android Studio durch `Analyze > Inspect Code…`)
https://github.com/luk-pe/BullshitBingo/blob/521b8f1b45c28bb03cac765488cab6481afaff8b/app/src/main/java/com/example/lukaspeter/bullshitbingo/activities/NewGameActivity.java#L57

**Comment by luk-pe** [comment]
behoben durch commit 893bc254266f581dcc5b84f368f00f2ae1a9d8b4
