### ISSUE TITLE
Vorschlag: zwei Zeilen zusammenfassen

### ISSUE THREAD

**Issue by behrends** [luk-pe/BullshitBingo#4]
hier könnte direkt ein `return` stehen (ohne vorher eine Variable zu deklarieren)
https://github.com/luk-pe/BullshitBingo/blob/521b8f1b45c28bb03cac765488cab6481afaff8b/app/src/main/java/com/example/lukaspeter/bullshitbingo/fragments/BrowseFragment.java#L42-L43

**Comment by luk-pe** [comment]
behoben in allen Fragments durch commit 893bc254266f581dcc5b84f368f00f2ae1a9d8b4
