### ISSUE TITLE
Template-Erstellung optimierung

### ISSUE THREAD

**Issue by behrends** [luk-pe/BullshitBingo#6]
Vorschlag: 
Wenn bei `EditText` das Attribut `singleLine` auf `true` gesetzt wird, dann erhält man bei der Eingabe eines Items einen Knopf, mit dem man schnell zum nächsten Wechseln kann:

![test](https://user-images.githubusercontent.com/50868/53806668-da5bed00-3f4d-11e9-868c-e3c0daea9f4e.png)

Dadurch ist eine schnellere Eingabe mehrere Items möglich

**Comment by luk-pe** [comment]
Danke für den Tipp! Commit: e6c0ed425f528955dce661909f2f9d9bacc8da5d
